### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by holyboom1** [cyrax111/avatar_stack#1]
`======== Exception caught by widgets library =======================================================
The following UnsupportedError was thrown building LayoutBuilder:
Unsupported operation: Infinity or NaN toInt

The relevant error-causing widget was: 
  WidgetStack WidgetStack:lib/feature/presentation/widgets/main/header/main_header_widget.dart:164:25
When the exception was thrown, this was the stack: 
#0      double.toInt (dart:core-patch/double.dart)
#1      RestrictedPositions._calculateMaxCapacityItems (package:avatar_stack/src/positions/restricted_positions.dart:75:21)
#2      RestrictedPositions.calculate (package:avatar_stack/src/positions/restricted_positions.dart:64:48)
#3      WidgetStack.build.<anonymous closure> (package:avatar_stack/src/widget_stack.dart:35:29)
#4      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:122:31)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#6      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:154:12)
#7      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1962:59)
#8      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:910:15)
#9      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962:14)
#10     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228:7)
#11     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:317:5)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#13     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#15     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#17     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#18     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#19     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#20     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#21     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#22     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#31     _invoke (dart:ui/hooks.dart:150:10)
#32     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#33     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)`

**Comment by cyrax111** [comment]
@holyboom1  can you please provide a reproducible minimal code sample.

**Comment by holyboom1** [comment]
`class MainAppSplashScreen extends StatefulWidget {
        @override
        _MainAppSplashScreenState createState() => _MainAppSplashScreenState();
      }
      
      class _MainAppSplashScreenState extends State<MainAppSplashScreen> with TickerProviderStateMixin {
          return Scaffold(
      backgroundColor: AppColors.white,
      extendBody: true,
      body: Stack(
        children: [
          NestedScrollView(
            headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
              return [
                SliverPersistentHeader(
                  pinned: true,
                  floating: true,
                  delegate: AppBarOrange(),
                )
              ];
            },
            body: ListView(
              children: [
                Container(
                  width: 100,
                  height: 100,
                  color: Colors.green,
                ),
                Container(
                  width: 100,
                  height: 100,
                  color: Colors.red,
                ),
                Container(
                  width: 100,
                  height: 100,
                  color: Colors.green,
                ),
                Container(
                  width: 100,
                  height: 100,
                  color: Colors.red,
                ),


                        ],
                      )
                    ),
                  ],
                ),
              );
            }
          }
          
          
          class AppBarOrange extends SliverPersistentHeaderDelegate {
            final double minTopBarHeight = 100;
            final double maxTopBarHeight = 400;
          
            AppBarOrange();
          
            final settings = RestrictedPositions(
              maxCoverage: 0.7,
              minCoverage: 0.5,
              align: StackAlign.right,
            );
          
            @override
            Widget build(
                BuildContext context,
                double shrinkOffset,
                bool overlapsContent,
                ) {
              var shrinkFactor = min(1, shrinkOffset / (maxExtent - minExtent));
          
              var topBar = Container(
                color: Colors.orange,
                height: max(maxTopBarHeight * (1 - shrinkFactor * 1.3), minTopBarHeight),
                width: double.infinity,
                child: Stack(
                  clipBehavior: Clip.none,
                  children:[
                    Positioned(
                      top: 0,
                      child: Container(
                          width: 200,
                          height: max(maxTopBarHeight * (0.25 - shrinkFactor * 1), 0),
                          child: Opacity(
                            opacity: (1 - shrinkFactor.toDouble() * (1 + shrinkFactor * 60) > 0) ? 1 - shrinkFactor.toDouble() * (1 + shrinkFactor * 60) : 0,
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Container(
                                  padding: EdgeInsets.symmetric(vertical: max(maxTopBarHeight * (0.25 - shrinkFactor * 2), 0) / 8),
                                  width: 200,
                                  child:
                                  WidgetStack(
                                    positions: settings,
                                    stackedWidgets:
                                    List.generate(3, (index) {return Image.network('https://i.pinimg.com/236x/34/51/92/345192b3fd9f386fd89d5dfe49a2a6fd.jpg', width: 50, height: 50,);}),
                                    buildInfoWidget: (surplus) {
                                      return Text(
                                        '+$surplus',
                                      );
                                    },
                                  ),
          
                                )
                              ],
                            ),
                          )),
                    ),
                  ],
                )
              );
          
              return Container(
                height: max(maxExtent - shrinkOffset, minExtent),
                child: Stack(
                  children: [
                    if (shrinkFactor <= 0.5) topBar,
                    Align(
                      alignment: Alignment.bottomCenter,
                      child: Container(
                        alignment: Alignment.center,
                        width: double.infinity,
                        height: 100
                      ),
                    ),
                    if (shrinkFactor > 0.5) topBar,
                  ],
                ),
              );
            }

          @override
          double get maxExtent => 500;
        
          @override
          double get minExtent => 100;
        
          @override
          bool shouldRebuild(SliverPersistentHeaderDelegate oldDelegate) => true;
        }`


not minimal, but as is)
I found a line where the error disappears, but i'm need dynamic height, 

  `
            Positioned(
              child: Container(
                  width: 200,
                  height: max(maxTopBarHeight * (0.25 - shrinkFactor * 1), 0), // here height
  `

**Comment by cyrax111** [comment]
As you mentioned the problem was with `height`. I made the code more solid. You need to update the version of the package to [1.0.4](https://pub.dev/packages/avatar_stack).

Just add `avatar_stack: ^1.0.4` to dependencies, check and give me feedback please.

**Comment by holyboom1** [comment]
Yes fine ! everything is working ! Thank you!

**Comment by cyrax111** [comment]
You are welcome)
