### ISSUE TITLE
Ability to make vertical list

### ISSUE THREAD

**Issue by AndreasLyngholm** [cyrax111/avatar_stack#4]
Hi there,

I was looking for just this! I need to make the list vertical instead of horizontal. Is this possible?

Thanks in advance

**Comment by AndreasLyngholm** [comment]
@cyrax111 - is the project still being worked on?

**Comment by cyrax111** [comment]
Hi Andreas! Yes, I am working on this project )

**Comment by cyrax111** [comment]
Let me check

**Comment by cyrax111** [comment]
As a fast solution you can consider [RotatedBox](https://api.flutter.dev/flutter/widgets/RotatedBox-class.html) widget.

**Comment by cyrax111** [comment]
Updated an example

**Comment by AndreasLyngholm** [comment]
Thanks a lot! I will take a look

**Comment by AndreasLyngholm** [comment]
@cyrax111 The idea is correct, but all avatars are now also turned 270 degrees.

I cannot simply add another RotatedBox, since the avatars expect an instance of List<ImageProvider<Object>>

I hope you have another solution.

Thanks in advance!

**Comment by AndreasLyngholm** [comment]
I am able to modify the plugin so that each CircleAvatar is rotated the last 90 degrees. Could you make it possible to give a rotation argument when making the AvatarStack? Maybe that is the solution for now?

I would like to contribute to this project, if I end up using it.

Thanks in advance!

**Comment by cyrax111** [comment]
Can you show a picture of example that you want to achieve?

**Comment by AndreasLyngholm** [comment]
Sure!

I want to acieve what you can see in the top left corner of the screen.

![Screenshot 2023-03-19 175403](https://user-images.githubusercontent.com/10391836/226192202-8a676752-93ff-4f1d-9738-ce23bcd61a8c.png)

**Comment by AndreasLyngholm** [comment]
@cyrax111  :)

**Comment by cyrax111** [comment]
done :)

Added `layoutDirection` to Settings.

An example:
```dart
final settings = RestrictedPositions(
      maxCoverage: 0.3,
      minCoverage: 0.1,
      laying: const StackLaying(itemPositionNumberAtTop: 5),
      layoutDirection: LayoutDirection.vertical,
    );
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 15),
      child: Row(
        children: [
          const RotatedBox(quarterTurns: 3, child: Text('Vertical')),
          const SizedBox(width: 10),
          AvatarStack(
            width: 50,
            settings: settings,
            avatars: [
              for (var n = 0; n < 20; n++) NetworkImage(getAvatarUrl(n))
            ],
          ),
        ],
      ),
    );
```

**Comment by AndreasLyngholm** [comment]
Hi again @cyrax111,

Could you add the same change to WidgetStack? 👍 

Thanks in advance!

**Comment by cyrax111** [comment]
It's already done, just change `AvatarStack` to `WidgetStack` and wrap it to `SizedBox`.

```dart
Row(
  children: [
    const RotatedBox(
        quarterTurns: 3, child: Text('Vertical widget stack')),
    const SizedBox(width: 10),
    SizedBox(
      width: 50,
      child: WidgetStack(
        positions: settings,
        stackedWidgets: [
          for (var n = 0; n < 12; n++)
            FlutterLogo(
              style: FlutterLogoStyle.stacked,
              textColor: Color(0xFF * 0x1000000 +
                  n * 10 * 0x10000 +
                  (0xFF - n * 10) * 0x100),
            ),
          const FittedBox(
              fit: BoxFit.fitHeight,
              child: Text('A',
                  style: TextStyle(height: 0.9, color: Colors.orange))),
          const FittedBox(
              fit: BoxFit.fitHeight,
              child: Text('B', style: TextStyle(height: 0.9))),
          const FittedBox(
              fit: BoxFit.fitHeight,
              child: Text('C',
                  style: TextStyle(height: 0.9, color: Colors.green))),
        ],
        buildInfoWidget: (surplus) {
          return Center(
              child: Text(
            '+$surplus',
            style: Theme.of(context).textTheme.headlineSmall,
          ));
        },
      ),
    ),
  ],
),
```

**Comment by AndreasLyngholm** [comment]
Oh! My bad! 👍 

Great work! 🚀
