### ISSUE TITLE
Widget Stack make my image set rectangle?

### ISSUE THREAD

**Issue by minhnguyenandpad** [cyrax111/avatar_stack#5]
I follow this issue: https://github.com/cyrax111/avatar_stack/issues/2

And adjust my code and the image stack is set to rectangle. I try to change to circle but it not working

<img width="56" alt="Screen Shot 2023-03-22 at 15 05 15" src="https://user-images.githubusercontent.com/102590539/226838129-dda5e2aa-8376-43cf-a758-9c1b7c7c2b28.png">

**Comment by cyrax111** [comment]
You need to wrap your image to `CircleAvatar` or use `AvatarStack` instead of `WidgetStack`.

An example: 
```dart
class Example1Default extends StatelessWidget {
  const Example1Default({this.name = 'Default:', Key? key}) : super(key: key);

  final String name;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text(name),
        const SizedBox(height: 10),
        AvatarStack(
          height: 50,
          avatars: [for (var n = 0; n < 15; n++) NetworkImage(getAvatarUrl(n))],
        ),
      ],
    );
  }
}

String getAvatarUrl(int n) {
  final url = 'https://i.pravatar.cc/150?img=$n';
  return url;
}
```

Feel free to explore [examples](https://pub.dev/packages/avatar_stack/example).
