### ISSUE TITLE
RestrictedPositioned for WidgetStack is not exported on main file of the package

### ISSUE THREAD

**Issue by moshOntong-IT** [cyrax111/avatar_stack#7]
I cant use the RestrictedPositioned because it is not exported on avatar_stack/avatar_stack.dart

**Comment by cyrax111** [comment]
There are two libraries: 
- avatar_stack
- positions

_RestrictedPositioned_ is exported in **positions** library.

[https://pub.dev/documentation/avatar_stack/latest/positions/positions-library.html](https://pub.dev/documentation/avatar_stack/latest/positions/positions-library.html)

Please explore an [example](https://pub.dev/packages/avatar_stack/example).
